//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbapitoEntities : DbContext
    {
        public dbapitoEntities()
            : base("name=dbapitoEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Championship> Championship { get; set; }
        public virtual DbSet<Confederation> Confederation { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<NextMatch> NextMatch { get; set; }
        public virtual DbSet<Referee> Referee { get; set; }
        public virtual DbSet<Team> Team { get; set; }
    }
}
