//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int ChampionshipYear { get; set; }
        public string Link { get; set; }
        public int ChampionshipID { get; set; }
        public int Active { get; set; }
    
        public virtual Championship Championship { get; set; }
    }
}
